<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  
    <PackageId>PepperX.QueryForge</PackageId>
    <Version>2.1.0</Version>
    <Authors>Amir Hossein Morady Pour</Authors>
    <Description>Abstract, provider-agnostic foundation of the QueryForge ecosystem. It provides the core models, fluent builders, and bulletproof validation engines required to construct dynamic, paginated, and hierarchically grouped queries.</Description>
    <PackageTags>dynamic-query;query-builder;pagination;hierarchical-grouping;csharp;dotnet;json-validation;devextreme;ag-grid;kendo-ui;query-engine;filtering;sorting;abstract-core</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/PepperX-Dev/QueryForge/tree/main/src/PepperX.QueryForge</RepositoryUrl>
	<PackageIcon>icon.png</PackageIcon>
	  
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
	  
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
	<None Include="README.md" Pack="true" PackagePath="\" />
	<None Include="..\..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
