<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  
    <PackageId>PepperX.QueryForge</PackageId>
    <Version>1.0.1</Version>
    <Authors>Amir Hossein Morady Pour</Authors>
    <Description>A lightweight, provider-agnostic, dynamic query building and validation engine for .NET.</Description>
    <PackageTags>sql;query;builder;dynamic;pagination;grouping;linq;filter</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/amirhosseinmp02/PepperX</RepositoryUrl>
	<PackageIcon>icon.png</PackageIcon>
	  
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
	  
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
	<None Include="..\..\README.md" Pack="true" PackagePath="\" />
	<None Include="..\..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
