<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  
	<PackageId>PepperX.QueryForge.Dapper</PackageId>
	<Version>1.0.4</Version>
	<Authors>Amir Hossein Morady Pour</Authors>
	<Description>High-performance execution provider for the PepperX.QueryForge core library. It translates abstract query models into optimized SQL and executes them against Microsoft SQL Server using Dapper, seamlessly handling hierarchical grouping, complex filtering, and Stored Procedure/TVF integration.</Description>
	<PackageTags>sql;query;builder;dynamic;pagination;grouping;linq;filter</PackageTags>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<RepositoryUrl>https://github.com/amirhosseinmp02/PepperX/tree/main/src/PepperX.QueryForge.Dapper</RepositoryUrl>
	<PackageIcon>icon.png</PackageIcon>

	<IsPackable>true</IsPackable>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);1591</NoWarn>

	<IncludeSymbols>true</IncludeSymbols>
	<SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\PepperX.QueryForge\PepperX.QueryForge.csproj" />
	  
    <InternalsVisibleTo Include="PepperX.QueryForge.Dapper.Tests" />

	<None Include="README.md" Pack="true" PackagePath="\" />
	<None Include="..\..\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
  </ItemGroup>

</Project>
